#!/usr/bin/env bash

#
# -----------------------------------------------------------
#               01-setup-artifactory.sh
#
#  This is the "Architect" script for Artifactory.
#
#  1. Secrets Management:
#     - Checks 'cicd.env' for an existing Master Key.
#     - If missing, generates a secure 256-bit key and
#       SAVES IT BACK to 'cicd.env' to ensure persistence.
#
#  2. Blueprint Generation:
#     - Generates 'master.key' file (Encryption).
#     - Generates 'bootstrap.creds' file (Admin Reset).
#     - Generates 'system.yaml' (Infrastructure Config).
#
#  3. Permissions:
#     - Sets strict 0600 permissions for secrets.
#     - Sets UID 1030 ownership for all bind mounts.
# -----------------------------------------------------------

set -e
echo "Starting Artifactory 'Architect' Setup..."

# --- 1. Define Paths ---
# We use the standard "City" layout
ARTIFACTORY_BASE="$HOME/cicd_stack/artifactory"
VAR_ETC="$ARTIFACTORY_BASE/var/etc"

# Master Secrets File
MASTER_ENV_FILE="$HOME/cicd_stack/cicd.env"

# --- 2. Load & Persist Secrets ---
if [ ! -f "$MASTER_ENV_FILE" ]; then
    echo "ERROR: Master env file not found at $MASTER_ENV_FILE"
    echo "   Please create it before running this script."
    exit 1
fi

# Source the current environment
source "$MASTER_ENV_FILE"

echo "Checking for Master Key..."

# A. Check/Generate Master Key
# We use 32 bytes (64 hex chars) for 256-bit AES security.
if [ -z "$ARTIFACTORY_MASTER_KEY" ]; then
    echo "WARNING: ARTIFACTORY_MASTER_KEY not found in cicd.env."
    echo "    Generating a new persistent 256-bit Master Key..."

    # Generate high-entropy key (32 bytes = 256 bits)
    NEW_MASTER_KEY=$(openssl rand -hex 32)

    # Append to the master file so it persists for future runs
    echo "" >> "$MASTER_ENV_FILE"
    echo "# Artifactory Master Key (Generated by 01-setup-artifactory.sh)" >> "$MASTER_ENV_FILE"
    echo "ARTIFACTORY_MASTER_KEY=\"$NEW_MASTER_KEY\"" >> "$MASTER_ENV_FILE"

    # Update local variable
    ARTIFACTORY_MASTER_KEY="$NEW_MASTER_KEY"
    echo "Key generated and saved to cicd.env."
else
    echo "Found existing ARTIFACTORY_MASTER_KEY in cicd.env."
fi

# B. Check/Generate Admin Password
# This is only used on the very first bootstrap of the database.
if [ -z "$ARTIFACTORY_ADMIN_PASSWORD" ]; then
    echo "WARNING: ARTIFACTORY_ADMIN_PASSWORD not found in cicd.env."
    echo "    Generating a new initial admin password..."

    # Generate high-entropy password
    NEW_ADMIN_PASS="admin123$(openssl rand -hex 16)"

    echo "" >> "$MASTER_ENV_FILE"
    echo "# Artifactory Initial Admin Password" >> "$MASTER_ENV_FILE"
    echo "ARTIFACTORY_ADMIN_PASSWORD=\"$NEW_ADMIN_PASS\"" >> "$MASTER_ENV_FILE"

    ARTIFACTORY_ADMIN_PASSWORD="$NEW_ADMIN_PASS"
    echo "Password generated and saved to cicd.env."
else
     echo "Found existing ARTIFACTORY_ADMIN_PASSWORD in cicd.env."
fi

# --- 3. Create Directory Structure ---
echo "Creating configuration directories..."
mkdir -p "$VAR_ETC/security"
mkdir -p "$VAR_ETC/access"

# --- 4. Generate Secret Files ---
echo "Writing secret files..."

# A. master.key
KEY_FILE="$VAR_ETC/security/master.key"
echo -n "$ARTIFACTORY_MASTER_KEY" > "$KEY_FILE"
# IMPORTANT: Security requirement (0600)
chmod 600 "$KEY_FILE"

# B. bootstrap.creds
# This file is read by the Access service to reset the admin user
CREDS_FILE="$VAR_ETC/access/bootstrap.creds"
echo "admin@*=$ARTIFACTORY_ADMIN_PASSWORD" > "$CREDS_FILE"
# IMPORTANT: Security requirement (0600)
chmod 600 "$CREDS_FILE"

# --- 5. Generate 'system.yaml' Blueprint ---
# This configures the infrastructure: Ports, SSL, and Security.
SYSTEM_YAML="$VAR_ETC/system.yaml"
echo "Generating 'system.yaml' configuration..."

cat << EOF > "$SYSTEM_YAML"
shared:
  node:
    # We use the internal DNS hostname
    ip: artifactory.cicd.local

artifactory:
  tomcat:
    # Disable standard HTTP connector (default 8081)
    connector:
      enabled: false

    # Enable HTTPS connector on port 10500
    # This aligns with our host port mapping to prevent Split-Horizon issues.
    httpsConnector:
      enabled: true
      port: 10500
      # Paths inside the container (where we will mount the certs)
      certificateFile: "/var/opt/jfrog/artifactory/var/etc/security/ssl/artifactory.cicd.local.crt.pem"
      certificateKeyFile: "/var/opt/jfrog/artifactory/var/etc/security/ssl/artifactory.cicd.local.key.pem"

router:
  entrypoints:
    # Override default 8082 to match our host port 10501
    externalPort: 10501

# CRITICAL SECURITY SETTING
# We must disable the SSRF blacklist to allow webhooks to
# talk to local IPs (like 127.0.0.1) and internal DNS (jenkins.cicd.local).
event:
  security:
    blacklist:
      enabled: false
EOF
echo "   Done."

# --- 6. Permission Fix (UID 1030) ---
echo "Setting directory permissions..."
echo "   Artifactory runs as UID 1030. We must set ownership for bind mounts."

# We ensure the entire base directory is owned by 1030
if [ -d "$ARTIFACTORY_BASE" ]; then
    sudo chown -R 1030:1030 "$ARTIFACTORY_BASE"
    echo "Permissions set on $ARTIFACTORY_BASE"
else
    echo "ERROR: Directory $ARTIFACTORY_BASE was not created."
    exit 1
fi

echo ""
echo "Artifactory 'Architect' setup complete."
echo "   - Master Key:     $KEY_FILE"
echo "   - Admin Creds:    $CREDS_FILE"
echo "   - System Config:  $SYSTEM_YAML"
echo "   - Admin Pass:     $ARTIFACTORY_ADMIN_PASSWORD"