#!/usr/bin/env bash

#
# -----------------------------------------------------------
#               01-setup-artifactory.sh
#
#  This is the "Architect" script for Artifactory.
#
#  1. Secrets Management:
#     - Checks 'cicd.env' for an existing Master Key.
#     - If missing, generates a secure 256-bit key and
#       SAVES IT BACK to 'cicd.env' to ensure persistence.
#
#  2. Preparation (The "Claim"):
#     - Takes ownership AND write permissions of the config
#       directory so we can overwrite files safely.
#
#  3. Blueprint Generation:
#     - Generates 'master.key' file (Encryption).
#     - Generates 'bootstrap.creds' file (Admin Reset).
#     - Generates 'system.yaml' (Infrastructure Config).
#
#  4. Permissions (The "Handover"):
#     - Sets strict 0600 permissions for secrets.
#     - Sets UID 1030 ownership for the container to use.
# -----------------------------------------------------------

set -e
echo "Starting Artifactory 'Architect' Setup..."

# --- 1. Define Paths ---
ARTIFACTORY_BASE="$HOME/cicd_stack/artifactory"
VAR_ETC="$ARTIFACTORY_BASE/var/etc"

# Master Secrets File
MASTER_ENV_FILE="$HOME/cicd_stack/cicd.env"

# Source Certs (from Article 2)
CA_CERT_PATH="$HOME/cicd_stack/ca/pki/certs/ca.pem"
SERVICE_CERT_PATH="$HOME/cicd_stack/ca/pki/services/artifactory.cicd.local/artifactory.cicd.local.crt.pem"
SERVICE_KEY_PATH="$HOME/cicd_stack/ca/pki/services/artifactory.cicd.local/artifactory.cicd.local.key.pem"

# --- 2. Load & Persist Secrets ---
if [ ! -f "$MASTER_ENV_FILE" ]; then
    echo "ERROR: Master env file not found at $MASTER_ENV_FILE"
    echo "   Please create it before running this script."
    exit 1
fi

# Source the current environment
source "$MASTER_ENV_FILE"

echo "Checking for Master Key..."

# A. Check/Generate Master Key
if [ -z "$ARTIFACTORY_MASTER_KEY" ]; then
    echo "WARNING: ARTIFACTORY_MASTER_KEY not found in cicd.env."
    echo "    Generating a new persistent 256-bit Master Key..."

    # Generate high-entropy key (32 bytes = 256 bits)
    NEW_MASTER_KEY=$(openssl rand -hex 32)

    # Append to the master file so it persists for future runs
    echo "" >> "$MASTER_ENV_FILE"
    echo "# Artifactory Master Key (Generated by 01-setup-artifactory.sh)" >> "$MASTER_ENV_FILE"
    echo "ARTIFACTORY_MASTER_KEY=\"$NEW_MASTER_KEY\"" >> "$MASTER_ENV_FILE"

    # Update local variable
    ARTIFACTORY_MASTER_KEY="$NEW_MASTER_KEY"
    echo "Key generated and saved to cicd.env."
else
    echo "Found existing ARTIFACTORY_MASTER_KEY in cicd.env."
fi

# B. Check/Generate Admin Password
if [ -z "$ARTIFACTORY_ADMIN_PASSWORD" ]; then
    echo "WARNING: ARTIFACTORY_ADMIN_PASSWORD not found in cicd.env."
    echo "    Generating a new initial admin password..."

    # Generate high-entropy password
    NEW_ADMIN_PASS="admin123$(openssl rand -hex 16)"

    echo "" >> "$MASTER_ENV_FILE"
    echo "# Artifactory Initial Admin Password" >> "$MASTER_ENV_FILE"
    echo "ARTIFACTORY_ADMIN_PASSWORD=\"$NEW_ADMIN_PASS\"" >> "$MASTER_ENV_FILE"

    ARTIFACTORY_ADMIN_PASSWORD="$NEW_ADMIN_PASS"
    echo "Password generated and saved to cicd.env."
else
     echo "Found existing ARTIFACTORY_ADMIN_PASSWORD in cicd.env."
fi

# --- 3. Claim Ownership & Write Permissions ---
# If the directory exists, we ensure we own it AND can write to it.
if [ -d "$ARTIFACTORY_BASE" ]; then
    echo "Claiming ownership and write access for $ARTIFACTORY_BASE..."
    sudo chown -R $(id -u):$(id -g) "$ARTIFACTORY_BASE"
    sudo chmod -R u+w "$ARTIFACTORY_BASE"
fi

# --- 4. Create Directory Structure ---
echo "Creating configuration directories..."
mkdir -p "$VAR_ETC/security/ssl"
mkdir -p "$VAR_ETC/security/keys/trusted"
mkdir -p "$VAR_ETC/access"

# --- 5. Stage Certificates ---
echo "Staging certificates..."

# A. Copy Service Certs (For HTTPS UI)
if [ -f "$SERVICE_CERT_PATH" ] && [ -f "$SERVICE_KEY_PATH" ]; then
    cp -f "$SERVICE_CERT_PATH" "$VAR_ETC/security/ssl/"
    cp -f "$SERVICE_KEY_PATH" "$VAR_ETC/security/ssl/"
    echo "   - HTTPS Certificates copied."
else
    echo "ERROR: Artifactory certificates not found at:"
    echo "   $SERVICE_CERT_PATH"
    echo "   Please run Article 2 scripts first."
    exit 1
fi

# B. Copy Root CA (For Outbound Trust)
if [ -f "$CA_CERT_PATH" ]; then
    cp -f "$CA_CERT_PATH" "$VAR_ETC/security/keys/trusted/"
    echo "   - Root CA copied to trusted directory."
else
    echo "ERROR: Root CA not found at $CA_CERT_PATH"
    exit 1
fi

# --- 6. Generate Secret Files ---
echo "Writing secret files..."

# A. master.key
KEY_FILE="$VAR_ETC/security/master.key"
echo -n "$ARTIFACTORY_MASTER_KEY" > "$KEY_FILE"
# IMPORTANT: Security requirement (0600)
chmod 600 "$KEY_FILE"

# B. bootstrap.creds
# This file is read by the Access service to reset the admin user
CREDS_FILE="$VAR_ETC/access/bootstrap.creds"
echo "admin@*=$ARTIFACTORY_ADMIN_PASSWORD" > "$CREDS_FILE"
# IMPORTANT: Security requirement (0600)
chmod 600 "$CREDS_FILE"

# --- 7. Generate 'system.yaml' Blueprint ---
# This configures the infrastructure: Ports, SSL, and Security.
SYSTEM_YAML="$VAR_ETC/system.yaml"
echo "Generating 'system.yaml' configuration..."

# FIXED: Removed invalid 'connector: enabled: false'
# FIXED: Corrected cert paths to remove extra '/var' to match mount point
cat << EOF > "$SYSTEM_YAML"
shared:
  node:
    # We use the internal DNS hostname
    ip: artifactory.cicd.local

artifactory:
  tomcat:
    # Enable HTTPS connector on port 10500
    httpsConnector:
      enabled: true
      port: 10500
      # Paths inside the container (mounted to /var/opt/jfrog/artifactory/etc/...)
      certificateFile: "/var/opt/jfrog/artifactory/etc/security/ssl/artifactory.cicd.local.crt.pem"
      certificateKeyFile: "/var/opt/jfrog/artifactory/etc/security/ssl/artifactory.cicd.local.key.pem"

router:
  entrypoints:
    # Override default 8082 to match our host port 10501
    externalPort: 10501

# CRITICAL SECURITY SETTING
# We must disable the SSRF blacklist to allow webhooks to
# talk to local IPs (like 127.0.0.1) and internal DNS (jenkins.cicd.local).
event:
  security:
    blacklist:
      enabled: false
EOF
echo "   Done."

# --- 8. Permission Handover (UID 1030) ---
echo "Setting directory permissions..."
echo "   Handing ownership to Artifactory UID 1030..."

if [ -d "$ARTIFACTORY_BASE" ]; then
    sudo chown -R 1030:1030 "$ARTIFACTORY_BASE"
    echo "Permissions set on $ARTIFACTORY_BASE"
else
    echo "ERROR: Directory $ARTIFACTORY_BASE was not created."
    exit 1
fi

echo ""
echo "Artifactory 'Architect' setup complete."
echo "   - Master Key:     $KEY_FILE"
echo "   - Admin Creds:    $CREDS_FILE"
echo "   - System Config:  $SYSTEM_YAML"
echo "   - Admin Pass:     $ARTIFACTORY_ADMIN_PASSWORD"