#!/usr/bin/env bash

#
# -----------------------------------------------------------
#               02-deploy-artifactory.sh
#
#  This is the "Deploy" script. It launches the Artifactory
#  container using the configuration generated by the
#  "Architect" script (01).
#
#  1. Preparation: Stops any running instance (Idempotency).
#  2. Network: Connects to 'cicd-net' with 'artifactory.cicd.local'.
#  3. Ports: Publishes 10500 (UI) and 10501 (Router) to localhost.
#  4. Mounts:
#     - Data Volume -> /var/opt/jfrog/artifactory (DB + Blobs)
#     - Config Dir  -> /var/opt/jfrog/artifactory/etc
#       (This overlay injects system.yaml, master.key,
#        bootstrap.creds, SSL certs, and the Root CA).
# -----------------------------------------------------------

set -e
echo "Deploying Artifactory..."

# --- 1. Define Paths ---
# Host Paths
ARTIFACTORY_BASE="$HOME/cicd_stack/artifactory"
VAR_ETC="$ARTIFACTORY_BASE/var/etc"

# Container Paths
# FIXED: The container expects config in 'etc' relative to the home dir,
# not 'var/etc'. The 'var' in the path is implied by the home location.
CONT_HOME="/var/opt/jfrog/artifactory"
CONT_VAR_ETC="$CONT_HOME/etc"

# --- 2. Stop and Remove Old Container ---
if [ "$(docker ps -q -f name=artifactory)" ]; then
    echo "Stopping existing 'artifactory' container..."
    docker stop artifactory
fi
if [ "$(docker ps -aq -f name=artifactory)" ]; then
    echo "Removing existing 'artifactory' container..."
    docker rm artifactory
fi

# --- 3. Run Artifactory ---
echo "Starting Artifactory container..."

# We use the OSS version.
# The mounts connect our host config (prepared in 01) to the
# container's runtime location.

docker run -d \
  --name artifactory \
  --restart always \
  --network cicd-net \
  --hostname artifactory.cicd.local \
  --publish 127.0.0.1:10500:10500 \
  --publish 127.0.0.1:10501:10501 \
  --volume artifactory-data:"$CONT_HOME" \
  --volume "$VAR_ETC":"$CONT_VAR_ETC" \
  releases-docker.jfrog.io/jfrog/artifactory-oss:latest

echo "Artifactory is starting."
echo "   This is a heavy Java application (PostgreSQL + Tomcat)."
echo "   It may take 2-5 minutes to initialize."
echo "   Monitor logs with: docker logs -f artifactory"
echo ""
echo "   Once ready, access the UI at: https://artifactory.cicd.local:10500"
echo "   Log in with: admin / <See output of 01-setup-artifactory.sh>"